# Generated by Django 4.2.5 on 2023-10-03 00:39

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20231003_0038'),
    ]

    operations = [
        TrigramExtension(),
    ]

